import { Recipe } from "../interfaces/recipe";

export const recipesTest: Recipe[] = [
    {
      "id": "1",
      "name": "Bolo de Chocolate",
      "category": "Sobremesa",
      "description": "Um delicioso bolo de chocolate para adoçar seu dia.",
      "ingredients": ["farinha", "açúcar", "ovos", "chocolate em pó", "leite", "óleo", "fermento"],
      "prepare": ["Misture os ingredientes secos.", "Adicione os líquidos e misture bem.", "Asse em forno pré-aquecido a 180°C por 40 minutos."],
      "image": "https://imgs.search.brave.com/OWd7RLOrQ3Kk-TBnPtJ0ZW-Zom1XEcT8HpWfjTTWnEU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMudmVjdGVlenku/Y29tL3N5c3RlbS9y/ZXNvdXJjZXMvcHJl/dmlld3MvMDA5Lzg4/Ny8xNzEvbm9uXzJ4/L2Nob2NvbGF0ZS1j/YWtlLWZyZWUtcG5n/LnBuZw",
      "videoTutorial": "https://youtube.com/exemplo-bolo-chocolate",
      "idCreator": "user123",
      "createdAt": "2023-10-01T10:00:00Z"
    },
    {
      "id": "2",
      "name": "Pizza Margherita",
      "category": "Prato Principal",
      "description": "Pizza clássica com molho de tomate, mussarela e manjericão.",
      "ingredients": ["massa de pizza", "molho de tomate", "mussarela", "manjericão", "azeite"],
      "prepare": ["Estique a massa.", "Espalhe o molho de tomate.", "Adicione a mussarela e leve ao forno.", "Finalize com manjericão e azeite."],
      "image": "https://exemplo.com/pizza-margherita.jpg",
      "videoTutorial": "https://youtube.com/exemplo-pizza-margherita",
      "idCreator": "user456",
      "createdAt": "2023-10-02T12:30:00Z"
    },
    {
      "id": "3",
      "name": "Salada Caesar",
      "category": "Entrada",
      "description": "Salada refrescante com croutons e molho Caesar.",
      "ingredients": ["alface", "croutons", "queijo parmesão", "molho Caesar", "frango grelhado"],
      "prepare": ["Lave e corte o alface.", "Adicione os croutons e o queijo.", "Regue com o molho Caesar.", "Coloque o frango grelhado por cima."],
      "image": "https://imgs.search.brave.com/OWd7RLOrQ3Kk-TBnPtJ0ZW-Zom1XEcT8HpWfjTTWnEU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMudmVjdGVlenku/Y29tL3N5c3RlbS9y/ZXNvdXJjZXMvcHJl/dmlld3MvMDA5Lzg4/Ny8xNzEvbm9uXzJ4/L2Nob2NvbGF0ZS1j/YWtlLWZyZWUtcG5n/LnBuZw",
      "videoTutorial": "https://youtube.com/exemplo-salada-caesar",
      "idCreator": "user789",
      "createdAt": "2023-10-03T15:45:00Z"
    },
    {
      "id": "4",
      "name": "Sushi de Salmão",
      "category": "Prato Principal",
      "description": "Sushi tradicional com salmão fresco.",
      "ingredients": ["arroz para sushi", "salmão fresco", "alga nori", "vinagre de arroz", "wasabi"],
      "prepare": ["Cozinhe o arroz e tempere com vinagre.", "Corte o salmão em fatias finas.", "Monte o sushi com o arroz e o salmão.", "Sirva com wasabi e molho de soja."],
      "image": "https://imgs.search.brave.com/OWd7RLOrQ3Kk-TBnPtJ0ZW-Zom1XEcT8HpWfjTTWnEU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMudmVjdGVlenku/Y29tL3N5c3RlbS9y/ZXNvdXJjZXMvcHJl/dmlld3MvMDA5Lzg4/Ny8xNzEvbm9uXzJ4/L2Nob2NvbGF0ZS1j/YWtlLWZyZWUtcG5n/LnBuZw",
      "videoTutorial": "https://youtube.com/exemplo-sushi-salmao",
      "idCreator": "user101",
      "createdAt": "2023-10-04T18:20:00Z"
    },
    {
      "id": "5",
      "name": "Torta de Maçã",
      "category": "Sobremesa",
      "description": "Torta caseira com maçãs caramelizadas.",
      "ingredients": ["maçãs", "açúcar", "canela", "massa folhada", "manteiga"],
      "prepare": ["Descasque e corte as maçãs.", "Caramelize as maçãs com açúcar e canela.", "Forre uma forma com a massa folhada.", "Asse em forno pré-aquecido a 180°C por 30 minutos."],
      "image": "https://imgs.search.brave.com/OWd7RLOrQ3Kk-TBnPtJ0ZW-Zom1XEcT8HpWfjTTWnEU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMudmVjdGVlenku/Y29tL3N5c3RlbS9y/ZXNvdXJjZXMvcHJl/dmlld3MvMDA5Lzg4/Ny8xNzEvbm9uXzJ4/L2Nob2NvbGF0ZS1j/YWtlLWZyZWUtcG5n/LnBuZw",
      "videoTutorial": "https://youtube.com/exemplo-torta-maca",
      "idCreator": "user112",
      "createdAt": "2023-10-05T09:15:00Z"
    },
    {
      "id": "6",
      "name": "Risoto de Cogumelos",
      "category": "Prato Principal",
      "description": "Risoto cremoso com cogumelos frescos.",
      "ingredients": ["arroz arbóreo", "cogumelos", "caldo de legumes", "cebola", "vinho branco", "queijo parmesão"],
      "prepare": ["Refogue a cebola e os cogumelos.", "Adicione o arroz e o vinho branco.", "Cozinhe adicionando o caldo aos poucos.", "Finalize com queijo parmesão."],
      "image": "https://imgs.search.brave.com/OWd7RLOrQ3Kk-TBnPtJ0ZW-Zom1XEcT8HpWfjTTWnEU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMudmVjdGVlenku/Y29tL3N5c3RlbS9y/ZXNvdXJjZXMvcHJl/dmlld3MvMDA5Lzg4/Ny8xNzEvbm9uXzJ4/L2Nob2NvbGF0ZS1j/YWtlLWZyZWUtcG5n/LnBuZw",
      "videoTutorial": "https://youtube.com/exemplo-risoto-cogumelos",
      "idCreator": "user131",
      "createdAt": "2023-10-06T14:50:00Z"
    },
    {
      "id": "7",
      "name": "Pão de Queijo",
      "category": "Lanche",
      "description": "Pão de queijo caseiro e quentinho.",
      "ingredients": ["polvilho azedo", "queijo minas", "leite", "óleo", "ovos"],
      "prepare": ["Misture todos os ingredientes.", "Modele os pães de queijo.", "Asse em forno pré-aquecido a 200°C por 20 minutos."],
      "image": "https://exemplo.com/pao-de-queijo.jpg",
      "videoTutorial": "https://youtube.com/exemplo-pao-de-queijo",
      "idCreator": "user151",
      "createdAt": "2023-10-07T11:05:00Z"
    },
    {
      "id": "8",
      "name": "Feijoada",
      "category": "Prato Principal",
      "description": "Feijoada completa com carne de porco e linguiça.",
      "ingredients": ["feijão preto", "carne de porco", "linguiça", "cebola", "alho", "louro"],
      "prepare": ["Cozinhe o feijão com as carnes.", "Refogue a cebola e o alho.", "Junte tudo e cozinhe até ficar bem temperado."],
      "image": "https://exemplo.com/feijoada.jpg",
      "videoTutorial": "https://youtube.com/exemplo-feijoada",
      "idCreator": "user171",
      "createdAt": "2023-10-08T16:40:00Z"
    },
    {
      "id": "9",
      "name": "Cupcake de Baunilha",
      "category": "Sobremesa",
      "description": "Cupcake fofinho com cobertura de baunilha.",
      "ingredients": ["farinha", "açúcar", "ovos", "leite", "baunilha", "fermento"],
      "prepare": ["Misture os ingredientes secos.", "Adicione os líquidos e misture bem.", "Asse em forminhas para cupcakes a 180°C por 20 minutos."],
      "image": "https://exemplo.com/cupcake-baunilha.jpg",
      "videoTutorial": "https://youtube.com/exemplo-cupcake-baunilha",
      "idCreator": "user191",
      "createdAt": "2023-10-09T13:25:00Z"
    },
    {
      "id": "10",
      "name": "Strogonoff de Frango",
      "category": "Prato Principal",
      "description": "Strogonoff cremoso com frango e cogumelos.",
      "ingredients": ["frango", "cogumelos", "creme de leite", "cebola", "molho de tomate"],
      "prepare": ["Refogue o frango e a cebola.", "Adicione os cogumelos e o molho de tomate.", "Finalize com o creme de leite."],
      "image": "https://exemplo.com/strogonoff-frango.jpg",
      "videoTutorial": "https://youtube.com/exemplo-strogonoff-frango",
      "idCreator": "user202",
      "createdAt": "2023-10-10T17:55:00Z"
    },
    {
      "id": "11",
      "name": "Pudim de Leite",
      "category": "Sobremesa",
      "description": "Pudim tradicional de leite condensado.",
      "ingredients": ["leite condensado", "leite", "ovos", "açúcar"],
      "prepare": ["Derreta o açúcar para fazer a calda.", "Bata os outros ingredientes no liquidificador.", "Asse em banho-maria por 1 hora."],
      "image": "https://exemplo.com/pudim-leite.jpg",
      "videoTutorial": "https://youtube.com/exemplo-pudim-leite",
      "idCreator": "user212",
      "createdAt": "2023-10-11T10:10:00Z"
    },
    {
      "id": "12",
      "name": "Lasanha à Bolonhesa",
      "category": "Prato Principal",
      "description": "Lasanha recheada com molho bolonhesa e queijo.",
      "ingredients": ["massa para lasanha", "carne moída", "molho de tomate", "queijo mussarela", "queijo parmesão"],
      "prepare": ["Cozinhe a carne moída com o molho de tomate.", "Monte a lasanha em camadas.", "Asse em forno pré-aquecido a 180°C por 40 minutos."],
      "image": "https://exemplo.com/lasanha-bolonhesa.jpg",
      "videoTutorial": "https://youtube.com/exemplo-lasanha-bolonhesa",
      "idCreator": "user222",
      "createdAt": "2023-10-12T14:35:00Z"
    },
    {
      "id": "13",
      "name": "Brigadeiro",
      "category": "Sobremesa",
      "description": "Brigadeiro cremoso e delicioso.",
      "ingredients": ["leite condensado", "chocolate em pó", "manteiga", "granulado"],
      "prepare": ["Misture o leite condensado, o chocolate e a manteiga.", "Cozinhe até desgrudar da panela.", "Faça bolinhas e role no granulado."],
      "image": "https://exemplo.com/brigadeiro.jpg",
      "videoTutorial": "https://youtube.com/exemplo-brigadeiro",
      "idCreator": "user232",
      "createdAt": "2023-10-13T19:00:00Z"
    },
    {
      "id": "14",
      "name": "Coxinha",
      "category": "Lanche",
      "description": "Coxinha de frango crocante e saborosa.",
      "ingredients": ["frango", "farinha de trigo", "leite", "manteiga", "temperos"],
      "prepare": ["Cozinhe o frango e desfie.", "Prepare a massa com farinha, leite e manteiga.", "Modele as coxinhas e frite."],
      "image": "https://exemplo.com/coxinha.jpg",
      "videoTutorial": "https://youtube.com/exemplo-coxinha",
      "idCreator": "user242",
      "createdAt": "2023-10-14T12:45:00Z"
    },
    {
      "id": "15",
      "name": "Cuscuz Paulista",
      "category": "Prato Principal",
      "description": "Cuscuz recheado com legumes e sardinha.",
      "ingredients": ["farinha de milho", "sardinha", "tomate", "cebola", "pimentão", "ervilha"],
      "prepare": ["Cozinhe a farinha de milho.", "Refogue os legumes e a sardinha.", "Monte o cuscuz em camadas e deixe gelar."],
      "image": "https://exemplo.com/cuscuz-paulista.jpg",
      "videoTutorial": "https://youtube.com/exemplo-cuscuz-paulista",
      "idCreator": "user252",
      "createdAt": "2023-10-15T16:20:00Z"
    },
    {
      "id": "16",
      "name": "Mousse de Maracujá",
      "category": "Sobremesa",
      "description": "Mousse leve e refrescante de maracujá.",
      "ingredients": ["suco de maracujá", "leite condensado", "creme de leite"],
      "prepare": ["Bata todos os ingredientes no liquidificador.", "Leve à geladeira por 2 horas."],
      "image": "https://exemplo.com/mousse-maracuja.jpg",
      "videoTutorial": "https://youtube.com/exemplo-mousse-maracuja",
      "idCreator": "user262",
      "createdAt": "2023-10-16T10:30:00Z"
    },
    {
      "id": "17",
      "name": "Acarajé",
      "category": "Lanche",
      "description": "Acarajé tradicional com vatapá e camarão.",
      "ingredients": ["feijão fradinho", "cebola", "sal", "vatapá", "camarão"],
      "prepare": ["Bata o feijão fradinho com cebola.", "Frite a massa em azeite de dendê.", "Recheie com vatapá e camarão."],
      "image": "https://exemplo.com/acaraje.jpg",
      "videoTutorial": "https://youtube.com/exemplo-acaraje",
      "idCreator": "user272",
      "createdAt": "2023-10-17T14:15:00Z"
    },
    {
      "id": "18",
      "name": "Canjica",
      "category": "Sobremesa",
      "description": "Canjica cremosa com leite condensado e canela.",
      "ingredients": ["canjica", "leite", "leite condensado", "açúcar", "canela"],
      "prepare": ["Cozinhe a canjica com leite e açúcar.", "Adicione o leite condensado e a canela.", "Sirva quente ou frio."],
      "image": "https://exemplo.com/canjica.jpg",
      "videoTutorial": "https://youtube.com/exemplo-canjica",
      "idCreator": "user282",
      "createdAt": "2023-10-18T18:50:00Z"
    },
    {
      "id": "19",
      "name": "Moqueca de Peixe",
      "category": "Prato Principal",
      "description": "Moqueca de peixe com azeite de dendê e leite de coco.",
      "ingredients": ["peixe", "cebola", "tomate", "pimentão", "azeite de dendê", "leite de coco"],
      "prepare": ["Tempere o peixe com sal e limão.", "Refogue os legumes e adicione o peixe.", "Cozinhe com azeite de dendê e leite de coco."],
      "image": "https://exemplo.com/moqueca-peixe.jpg",
      "videoTutorial": "https://youtube.com/exemplo-moqueca-peixe",
      "idCreator": "user292",
      "createdAt": "2023-10-19T12:25:00Z"
    },
    {
      "id": "20",
      "name": "Pavê de Chocolate",
      "category": "Sobremesa",
      "description": "Pavê de chocolate com biscoitos e creme.",
      "ingredients": ["biscoitos", "chocolate", "creme de leite", "leite condensado"],
      "prepare": ["Prepare o creme de chocolate.", "Monte o pavê em camadas de biscoitos e creme.", "Leve à geladeira por 4 horas."],
      "image": "https://exemplo.com/pave-chocolate.jpg",
      "videoTutorial": "https://youtube.com/exemplo-pave-chocolate",
      "idCreator": "user302",
      "createdAt": "2023-10-20T16:00:00Z"
    }
]